name: flutter_app_router
description: An advanced router for Flutter with support for parsing routes, parameters, and guards.
version: 1.0.0
homepage: https://github.com/arlamend7/flutter_flutter_app_router
repository: https://github.com/arlamend7/flutter_flutter_app_router
issue_tracker: https://github.com/arlamend7/flutter_flutter_app_router/issues
license: MIT

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
