name: Publish Flutter Package

on:
  push:
    branches:
      - master  # Runs only when master is updated

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Dry run publish
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: |
          mkdir -p ~/.pub-cache
          echo "${{ secrets.PUB_DEV_CREDENTIALS }}" > ~/.pub-cache/credentials.json
          flutter pub publish -f
        env:
          PUB_ENVIRONMENT: github-action
