name: Publish Package on Master Update

on:
  push:
    branches:
      - master # Triggers only on push to master

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Dry run publish
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: |
          mkdir -p ~/.pub-cache
          echo "${{ secrets.PUB_DEV_CREDENTIALS }}" > ~/.pub-cache/credentials.json
          dart pub publish -f
        env:
          PUB_ENVIRONMENT: github-action
