name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    permissions:
      id-token: write # For OIDC auth
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # working-directory: path/to/package/if/needed
      # If your package is in the root, no need to set working-directory
      environment: pub.dev
